import { Game } from './game.js';

Game.Constants = {
    GRAVITY: 0.5, JUMP_POWER: -12, ENEMY_TURN_DELAY: 500, PLATFORM_HEIGHT: 20, VERTICAL_GAP: 120,
    AWAN_HANTU_DETECTION_X_BASE: 60, AWAN_HANTU_DETECTION_Y: 50, AWAN_HANTU_PAUSE_DURATION: 30, AWAN_HANTU_DASH_SPEED: 8,
    EYE_SWEEP_RANGE: 4, ICICLE_SHAKE_DURATION: 40, ICICLE_FALL_SPEED: 7, ICICLE_WAIT_DURATION: 120, ICICLE_DETECTION_RANGE: 60,
    BAT_WAKE_DURATION: 15, BAT_FLIGHT_RANGE: 90, BAT_FLIGHT_SPEED: 2, BAT_DIP_HEIGHT: 70, BAT_FLIGHT_HEIGHT: 40, BAT_PATROL_END_DELAY: 120,
    BAT_DETECTION_RANGE_X: 400, BAT_ATTACK_RANGE_X: 95, BAT_DETECTION_RANGE_Y: 100, GROUND_MONSTER_ATTACK_RANGE: 120,
    ICE_PLATFORM_SHAKE_DURATION: 60, ICE_SHARD_LIFETIME: 90, ICE_SHARD_BLINK_RATE: 8, BLOCK_WIDTH: 40, LEVEL_SLOTS: 10,
    GAP_PROBABILITY: 0.35, MOVING_PLATFORM_PROB: 0.25, ICY_PLATFORM_PROB: 0.20, ICE_FRICTION: 0.98,
};