import { Game } from './game.js';

Game.State = {
    canvas: document.getElementById('game-canvas'),
    ctx: document.getElementById('game-canvas').getContext('2d'),
    startMenu: document.getElementById('start-menu'),
    startButton: document.getElementById('start-button'),
    gameOverMenu: document.getElementById('game-over-menu'),
    restartButton: document.getElementById('restart-button'),
    continueButton: document.getElementById('continue-button'),
    hud: document.getElementById('hud'),
    scoreDisplay: document.getElementById('score'),
    hpDisplay: document.getElementById('hp-hearts'),
    finalScoreDisplay: document.getElementById('final-score'),
    stageDisplay: document.getElementById('stage'),
    finalStageDisplay: document.getElementById('final-stage'),
    resetPlatformsButton: document.getElementById('reset-platforms-button'),
    stagePresetButtons: document.querySelectorAll('.stage-presets button'),
    characterSelectors: document.querySelectorAll('.char-select'),
    decorationSlider: document.getElementById('decoration-slider'),
    decorationValue: document.getElementById('decoration-value'),
    enemySelectionButtons: document.querySelectorAll('#enemy-selection button'),
    debugPlayerX: document.getElementById('debug-player-x'),
    debugPlayerY: document.getElementById('debug-player-y'),
    debugPlayerDX: document.getElementById('debug-player-dx'),
    debugPlayerDY: document.getElementById('debug-player-dy'),
    debugPlayerOnGround: document.getElementById('debug-player-onground'),
    debugCollision: document.getElementById('debug-collision'),
    mainContainer: document.querySelector('.main-container'),
    instructionsMenu: document.getElementById('instructions-menu'),
    instructionsButton: document.getElementById('instructions-button'),
    backToStartMenuButton: document.getElementById('back-to-start-menu-button'),
    debugCodeMenu: document.getElementById('debug-code-menu'),
    debugCodeInput: document.getElementById('debug-code-input'),
    debugCodeSubmit: document.getElementById('debug-code-submit'),
    nameInputMenu: document.getElementById('name-input-menu'),
    nameInputField: document.getElementById('name-input-field'),
    nameInputSubmit: document.getElementById('name-input-submit'),
    startHighscoreDisplay: document.getElementById('start-highscore-display'),
    refreshHighscoreBtn: document.getElementById('refresh-highscore-btn'),
    score: 0,
    gameOver: false,
    stage: 1,
    checkpointStage: 1,
    isTransitioning: false,
    landedYLevels: new Set(),
    globalAnimationTick: 0,
    selectedCharacter: 'ESKIMO',
    testEnemyType: 'GROUND_MONSTER',
    crumblingPlatformCandidate: null,
    crumbleCounter: 0,
    lastHangingEnemyType: 'BAT',
    userId: null,
    highScores: [],
    debugModeActive: false,
    secretCode: 'MTk2OA==',
    firebaseReady: false,
    player: {
        width: 30, height: 30, x: 0, y: 0, dx: 0, dy: 0,
        hp: 1, maxHp: 1,
        onGround: false, standingOnPlatform: null, isCrouching: false,
        canDropDown: true, platformToDropThrough: null,
        isHit: false, 
        hitTimer: 0,
        powerUp: null,
        powerUpCooldown: 0,
        direction: 'right',
        isAttacking: false,
        attackTimer: 0,
        isBlocking: false,
    },
    enemies: [],
    platforms: [],
    projectiles: [],
    powerUps: [],
    goalPlatform: null,
    decorations: [],
    showcaseCharacters: [],
    playerSpeed: 3,
    friction: 0.97,
    enemySpeed: 1,
    jumpDelay: 500,
    canJump: true,
    decorationProbability: 0.50
};